name: verify unit tests count

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  collect-and-verify:
    if: github.repository == 'openedx/edx-platform' || github.repository == 'edx/edx-platform-private'
    runs-on: [ edx-platform-runner ]
    steps:
      - name: sync directory owner
        run: sudo chown runner:runner -R .*

      - uses: actions/checkout@v2
      - name: install requirements
        run: |
          sudo pip install -r requirements/pip.txt
          sudo pip install -r requirements/edx/testing.txt

      - name: verify unit tests count
        uses: ./.github/actions/verify-tests-count
